Criando cógido HTML do currículo
limmatamara/curriculo pull request #1
Opened 2021-05-14 00:31 UTC by limmatamara

2021-05-14 00:40 UTC, jefferson-lima requested changes

2021-05-14 00:40 UTC, jefferson-lima commented on index.html
> +<body;>
Remover ;
```suggestion
<body>
```

2021-05-14 00:40 UTC, jefferson-lima commented on index.html
> +        <div class="titulos">
Você poderia utilizar uma lista aqui

2021-05-14 00:40 UTC, jefferson-lima commented on index.html
> +</body;>
Remover ;
```suggestion
</body>
```

2021-05-14 00:40 UTC, jefferson-lima commented on index.html
> +            Email: limmatamara@gmail.com<br/>
Poderia usar um link com mailto

https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/a

2021-05-15 00:55 UTC, jefferson-lima commented on index.html
> +            <ul>
Essa lista poderia estar dentro de uma tag `<address>`.
https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/address

2021-05-15 00:56 UTC, jefferson-lima commented on index.html
> +                11/05/2018 – 14/12/2020<br/>
Esse texto poderia estar dentro de uma tag `<p>`

2021-05-15 00:57 UTC, jefferson-lima commented on index.html
> +            Superior Tecnológico. UNINASSAU.<br/>
Usa um <p> aqui ao invés de quebrar a linha

2021-05-15 16:13 UTC, limmatamara commented on index.html
> +            Superior Tecnológico. UNINASSAU.<br/>
Não apareceu no comentário o que era pra usar no lugar da quebra de linha

2021-05-15 20:19 UTC, jefferson-lima approved these changes

2021-05-18 14:00 UTC, merged